// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  EthereumCall,
  EthereumEvent,
  SmartContract,
  EthereumValue,
  JSONValue,
  TypedMap,
  Entity,
  EthereumTuple,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class ModuleRegistryChanged extends EthereumEvent {
  get params(): ModuleRegistryChanged__Params {
    return new ModuleRegistryChanged__Params(this);
  }
}

export class ModuleRegistryChanged__Params {
  _event: ModuleRegistryChanged;

  constructor(event: ModuleRegistryChanged) {
    this._event = event;
  }

  get addr(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class WalletImplementationChanged extends EthereumEvent {
  get params(): WalletImplementationChanged__Params {
    return new WalletImplementationChanged__Params(this);
  }
}

export class WalletImplementationChanged__Params {
  _event: WalletImplementationChanged;

  constructor(event: WalletImplementationChanged) {
    this._event = event;
  }

  get addr(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class ENSManagerChanged extends EthereumEvent {
  get params(): ENSManagerChanged__Params {
    return new ENSManagerChanged__Params(this);
  }
}

export class ENSManagerChanged__Params {
  _event: ENSManagerChanged;

  constructor(event: ENSManagerChanged) {
    this._event = event;
  }

  get addr(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class ENSResolverChanged extends EthereumEvent {
  get params(): ENSResolverChanged__Params {
    return new ENSResolverChanged__Params(this);
  }
}

export class ENSResolverChanged__Params {
  _event: ENSResolverChanged;

  constructor(event: ENSResolverChanged) {
    this._event = event;
  }

  get addr(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class WalletCreated extends EthereumEvent {
  get params(): WalletCreated__Params {
    return new WalletCreated__Params(this);
  }
}

export class WalletCreated__Params {
  _event: WalletCreated;

  constructor(event: WalletCreated) {
    this._event = event;
  }

  get _wallet(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get _owner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class ManagerAdded extends EthereumEvent {
  get params(): ManagerAdded__Params {
    return new ManagerAdded__Params(this);
  }
}

export class ManagerAdded__Params {
  _event: ManagerAdded;

  constructor(event: ManagerAdded) {
    this._event = event;
  }

  get _manager(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class ManagerRevoked extends EthereumEvent {
  get params(): ManagerRevoked__Params {
    return new ManagerRevoked__Params(this);
  }
}

export class ManagerRevoked__Params {
  _event: ManagerRevoked;

  constructor(event: ManagerRevoked) {
    this._event = event;
  }

  get _manager(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class OwnerChanged extends EthereumEvent {
  get params(): OwnerChanged__Params {
    return new OwnerChanged__Params(this);
  }
}

export class OwnerChanged__Params {
  _event: OwnerChanged;

  constructor(event: OwnerChanged) {
    this._event = event;
  }

  get _newOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class WalletFactory extends SmartContract {
  static bind(address: Address): WalletFactory {
    return new WalletFactory("WalletFactory", address);
  }

  getENSReverseRegistrar(): Address {
    let result = super.call("getENSReverseRegistrar", []);
    return result[0].toAddress();
  }

  getENSRegistry(): Address {
    let result = super.call("getENSRegistry", []);
    return result[0].toAddress();
  }

  ensManager(): Address {
    let result = super.call("ensManager", []);
    return result[0].toAddress();
  }

  ADDR_REVERSE_NODE(): Bytes {
    let result = super.call("ADDR_REVERSE_NODE", []);
    return result[0].toBytes();
  }

  walletImplementation(): Address {
    let result = super.call("walletImplementation", []);
    return result[0].toAddress();
  }

  owner(): Address {
    let result = super.call("owner", []);
    return result[0].toAddress();
  }

  resolveEns(_node: Bytes): Address {
    let result = super.call("resolveEns", [
      EthereumValue.fromFixedBytes(_node)
    ]);
    return result[0].toAddress();
  }

  ensResolver(): Address {
    let result = super.call("ensResolver", []);
    return result[0].toAddress();
  }

  moduleRegistry(): Address {
    let result = super.call("moduleRegistry", []);
    return result[0].toAddress();
  }

  managers(param0: Address): boolean {
    let result = super.call("managers", [EthereumValue.fromAddress(param0)]);
    return result[0].toBoolean();
  }
}

export class ChangeModuleRegistryCall extends EthereumCall {
  get inputs(): ChangeModuleRegistryCall__Inputs {
    return new ChangeModuleRegistryCall__Inputs(this);
  }

  get outputs(): ChangeModuleRegistryCall__Outputs {
    return new ChangeModuleRegistryCall__Outputs(this);
  }
}

export class ChangeModuleRegistryCall__Inputs {
  _call: ChangeModuleRegistryCall;

  constructor(call: ChangeModuleRegistryCall) {
    this._call = call;
  }

  get _moduleRegistry(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class ChangeModuleRegistryCall__Outputs {
  _call: ChangeModuleRegistryCall;

  constructor(call: ChangeModuleRegistryCall) {
    this._call = call;
  }
}

export class AddManagerCall extends EthereumCall {
  get inputs(): AddManagerCall__Inputs {
    return new AddManagerCall__Inputs(this);
  }

  get outputs(): AddManagerCall__Outputs {
    return new AddManagerCall__Outputs(this);
  }
}

export class AddManagerCall__Inputs {
  _call: AddManagerCall;

  constructor(call: AddManagerCall) {
    this._call = call;
  }

  get _manager(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class AddManagerCall__Outputs {
  _call: AddManagerCall;

  constructor(call: AddManagerCall) {
    this._call = call;
  }
}

export class RevokeManagerCall extends EthereumCall {
  get inputs(): RevokeManagerCall__Inputs {
    return new RevokeManagerCall__Inputs(this);
  }

  get outputs(): RevokeManagerCall__Outputs {
    return new RevokeManagerCall__Outputs(this);
  }
}

export class RevokeManagerCall__Inputs {
  _call: RevokeManagerCall;

  constructor(call: RevokeManagerCall) {
    this._call = call;
  }

  get _manager(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class RevokeManagerCall__Outputs {
  _call: RevokeManagerCall;

  constructor(call: RevokeManagerCall) {
    this._call = call;
  }
}

export class ChangeENSManagerCall extends EthereumCall {
  get inputs(): ChangeENSManagerCall__Inputs {
    return new ChangeENSManagerCall__Inputs(this);
  }

  get outputs(): ChangeENSManagerCall__Outputs {
    return new ChangeENSManagerCall__Outputs(this);
  }
}

export class ChangeENSManagerCall__Inputs {
  _call: ChangeENSManagerCall;

  constructor(call: ChangeENSManagerCall) {
    this._call = call;
  }

  get _ensManager(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class ChangeENSManagerCall__Outputs {
  _call: ChangeENSManagerCall;

  constructor(call: ChangeENSManagerCall) {
    this._call = call;
  }
}

export class ChangeOwnerCall extends EthereumCall {
  get inputs(): ChangeOwnerCall__Inputs {
    return new ChangeOwnerCall__Inputs(this);
  }

  get outputs(): ChangeOwnerCall__Outputs {
    return new ChangeOwnerCall__Outputs(this);
  }
}

export class ChangeOwnerCall__Inputs {
  _call: ChangeOwnerCall;

  constructor(call: ChangeOwnerCall) {
    this._call = call;
  }

  get _newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class ChangeOwnerCall__Outputs {
  _call: ChangeOwnerCall;

  constructor(call: ChangeOwnerCall) {
    this._call = call;
  }
}

export class CreateWalletCall extends EthereumCall {
  get inputs(): CreateWalletCall__Inputs {
    return new CreateWalletCall__Inputs(this);
  }

  get outputs(): CreateWalletCall__Outputs {
    return new CreateWalletCall__Outputs(this);
  }
}

export class CreateWalletCall__Inputs {
  _call: CreateWalletCall;

  constructor(call: CreateWalletCall) {
    this._call = call;
  }

  get _owner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _modules(): Array<Address> {
    return this._call.inputValues[1].value.toAddressArray();
  }

  get _label(): string {
    return this._call.inputValues[2].value.toString();
  }
}

export class CreateWalletCall__Outputs {
  _call: CreateWalletCall;

  constructor(call: CreateWalletCall) {
    this._call = call;
  }
}

export class ChangeWalletImplementationCall extends EthereumCall {
  get inputs(): ChangeWalletImplementationCall__Inputs {
    return new ChangeWalletImplementationCall__Inputs(this);
  }

  get outputs(): ChangeWalletImplementationCall__Outputs {
    return new ChangeWalletImplementationCall__Outputs(this);
  }
}

export class ChangeWalletImplementationCall__Inputs {
  _call: ChangeWalletImplementationCall;

  constructor(call: ChangeWalletImplementationCall) {
    this._call = call;
  }

  get _walletImplementation(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class ChangeWalletImplementationCall__Outputs {
  _call: ChangeWalletImplementationCall;

  constructor(call: ChangeWalletImplementationCall) {
    this._call = call;
  }
}

export class ChangeENSResolverCall extends EthereumCall {
  get inputs(): ChangeENSResolverCall__Inputs {
    return new ChangeENSResolverCall__Inputs(this);
  }

  get outputs(): ChangeENSResolverCall__Outputs {
    return new ChangeENSResolverCall__Outputs(this);
  }
}

export class ChangeENSResolverCall__Inputs {
  _call: ChangeENSResolverCall;

  constructor(call: ChangeENSResolverCall) {
    this._call = call;
  }

  get _ensResolver(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class ChangeENSResolverCall__Outputs {
  _call: ChangeENSResolverCall;

  constructor(call: ChangeENSResolverCall) {
    this._call = call;
  }
}

export class ConstructorCall extends EthereumCall {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _ensRegistry(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _moduleRegistry(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _walletImplementation(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get _ensManager(): Address {
    return this._call.inputValues[3].value.toAddress();
  }

  get _ensResolver(): Address {
    return this._call.inputValues[4].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}
